# Generated by Django 4.0.3 on 2022-06-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_cg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='loft',
            field=models.FloatField(null=True),
        ),
    ]
