# Generated by Django 4.0.3 on 2022-06-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_mydashapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydashapp',
            name='display_name',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
